@startuml

' 这是单行注释

/'
这是多行注释
这是多行注释
这是多行注释
这是多行注释
'/

Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
@enduml