@startuml
'The title keyword is used to add a title to the page.
'Pages can display headers and footers using header and footer.

header Page Header
footer Page %page% of %lastpage%
title Example Title

Alice -> Bob : message 1
Alice -> Bob : message 2

@enduml