@startuml
'可以使用 note left of， note right of 或 note over 在节点 (participant) 的相对位置放置注释。
'还可以通过修改背景色来高亮显示注释。
'以及使用关键字 end note 来添加多行注释。

participant Alice
participant Bob

note left of Alice #aqua
这是Alice左边的备注
end note

note right of Alice: 这是Alice右边的备注

note over Alice: 这是Alice上的备注

note over Alice, Bob #FFAAAA: 这是显示在\n Bob 和 Alice之间的备注.

note over Bob, Alice
This is yet another
example of
a long note.
end note

@enduml