@startuml
'如果只想关注部分图示，你可以使用进入和发出箭头。
'使用方括号 "[" 与 "]" 分别表示图示的左、右两侧。

[-> A: DoWork
activate A

A -> A: Internal call
activate A

A ->] : << createRequest >>
A<--] : RequestCreated

deactivate A

[<- A: Done

deactivate A

@enduml