@startuml
'关键字 autonumber 用于自动对消息编号。

autonumber
Bob -> Alice : Authentication Request
Bob <- Alice : Authentication Response

'autonumber start 用于指定编号的初始值，

autonumber 15
Bob -> Alice : Another authentication Request
Bob <- Alice : Another authentication Response

'autonumber start increment 可以同时指定编号的初始值和每次增加的值。
autonumber 40 10
Bob -> Alice : Yet another authentication Request
Bob <- Alice : Yet another authentication Response


@enduml